# Check new version.
checkVersion: true

database:
  # Database type. (sqlite/mysql)
  type: sqlite
  sqlite:
    file: "autopermission.db"
  mysql:
    host: "localhost:3306"
    name: "autopermission"
    username: "root"
    password: "your_mysql_password"
    properties:
      "useSSL": "false"
      # encoding
      #"useUnicode": "true"
      #"characterEncoding": "UTF-8"
      #"characterSetResults": "UTF-8"
      # performance
      "maintainTimeStats": "false"
      "elideSetAutoCommits": "true"
      "useLocalSessionState": "true"
      "alwaysSendSetIsolation": "false"
      "cacheServerConfiguration": "true"
      "cachePrepStmts": "true"
      "prepStmtCacheSize": "250"
      "prepStmtCacheSqlLimit": "2048"
      #"useServerPrepStmts": "true"
  connectionPool:
    # -1 is default
    maximumPoolSize: -1
    minimumIdle: -1
    maxLifetime: -1
    connectionTimeout: -1
    idleTimeout: -1

# Don't touch!
version: 1
