# Check new version.
checkVersion: true

# Set the time until promotion to a new group.
# syntax: <number><unit>: <group>
# unit = [d]ay/[h]our/[m]inute
permission:
  30m: "beginner"
  1d12h: "resident"
  10d: "super"

# Specify group priority.
# Prevent users from being added to the wrong group when they belong to a higher group.
priority:
  # Lower
  - "default"
  - "beginner"
  - "resident"
  - "super"
  - "moderator"
  - "administrator"
  # Higher

database:
  # Database type. (sqlite/mysql)
  type: sqlite
  sqlite:
    file: "autopermission.db"
  mysql:
    host: "localhost:3306"
    name: "autopermission"
    username: "root"
    password: "your_mysql_password"
    properties:
      "useSSL": "false"
      #"useUnicode": "true"
      #"characterEncoding": "UTF-8"
      #"characterSetResults": "UTF-8"
      "maintainTimeStats": "false"
      "elideSetAutoCommits": "true"
      "useLocalSessionState": "true"
      "alwaysSendSetIsolation": "false"
      "cacheServerConfiguration": "true"
      "cachePrepStmts": "true"
      "prepStmtCacheSize": "250"
      "prepStmtCacheSqlLimit": "2048"
      #"useServerPrepStmts": "true"
  connectionPool:
    # -1 is default
    maximumPoolSize: -1
    minimumIdle: -1
    maxLifetime: -1
    connectionTimeout: -1
    idleTimeout: -1

# Don't touch!
version: 1
